const c1= 'I was thrilled to be selected as a Web Development intern at Next24 Technologies, a dynamic startup based in Noida. This opportunity came through the government internship portal AICTE and spanned two months in an online format. Each week, I received various tasks that I needed to complete before their respective deadlines and present during our weekly meetings. My responsibilities ranged from creating Figma designs and implementing frontend features to handling backend operations like authentication, validation, and session management. Additionally, I worked on developing parody websites and continually expanded my knowledge by learning new concepts.';

const c2 = 'I built an interactive card details form, ensuring it closely matched the provided design. For this project, I had the freedom to use any tools, allowing me to practice and experiment with various technologies. The form I developed enables users to fill in their card details and see real-time updates on the card image. It also provides error messages upon submission if any input field is empty or if the card number, expiry date, or CVC fields are incorrectly formatted. Additionally, the form adapts to different screen sizes for an optimal layout and includes hover, active, and focus states for all interactive elements..';

const c3= "BlogBase is a versatile blogging platform that allows users to create or log into their accounts to publish blog posts. These posts are accessible to everyone on the platform, enabling them to view, like, share, comment, and even dislike the content.";

const c4 = 'I developed a comprehensive e-commerce website, equipped with essential features like wishlist, shopping cart, comments, reviews, ratings, and user account creation with validation. For the backend, I utilized the Mongoose and Express.js libraries to handle database operations and implemented an MVC model structure to efficiently manage routes, views, models, and controllers.';

const c5 = 'Leveraging the official GitHub API endpoints, I replicated and customized GitHub profile pages for both mobile and desktop views for any valid GitHub username. I utilized the JavaScript Fetch API to interact with the GitHub API, retrieving the necessary information from the JSON responses to dynamically populate the profile pages.';

const c6 = 'I successfully completed a challenge to build a multi-step form, ensuring it closely matched the provided design. For this project, I had the flexibility to use any tools, allowing me to practice and experiment with various technologies. The form I developed allows users to complete each step of the sequence, return to previous steps to update their selections, and view a summary of their choices in the final step before confirming their order. It also adapts to different screen sizes for an optimal layout and includes hover and focus states for all interactive elements. Additionally, the form provides validation messages if any field is missed, the email address is incorrectly formatted, or if a step is submitted without a selection..';

const c7 = 'I built an age calculator app, ensuring it closely matched the provided design. For this project, I had the flexibility to use any tools, allowing me to practice and experiment with various technologies. The app I developed allows users to submit a valid date through the form and view their age in years, months, and days. It includes validation errors if any field is empty, the day number is not between 1-31, the month number is not between 1-12, the date is in the future, or the date is invalid (e.g., 31/04/1991, as April has 30 days). Additionally, the app adapts to different screen sizes for an optimal layout and includes hover and focus states for all interactive elements. As a bonus, the age numbers animate to their final values when the form is submitted.';

const c8 = 'I developed a fully functional chat platform that allows users to engage in real-time conversations. By simply searching for a valid username, users can initiate chats seamlessly. This platform supports user authentication, ensuring secure and private messaging. Additionally, it includes features such as user presence indicators, message notifications, and a responsive design that adapts to various device sizes, enhancing the overall user experience.';

export {c1, c2, c3, c4, c5, c6, c7, c8};